services:
  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: client_side
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - express

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
